### ISSUE TITLE
Ghosting in Crit doe's not allow you to Re enter your body

### ISSUE THREAD

**Issue by danzargar** [AffectedArc07/Beatnik-Station#21]
as said in title this also kinda brake's the wizard spell named bind soul that makes you a Lich and if you try and use it spawns your body but doe's not put you in it

**Comment by danzargar** [comment]
Nah i mean in Critical condition not in the green

**Comment by praisenarsie** [comment]
> if you ghost while still alive you cant re-enter your body thats how its supposed to work

crit still means you're still alive, you're supposed to "succumb", not "ghost" when in crit

**Comment by danzargar** [comment]
this mainly just a small quality of life change i'd like ghost is a lot more easy to type then succumb and i don't remember succumb being in the ooc tab like ghost is

**Comment by danzargar** [comment]
Ok nevermind i am retarded point and laugh at me
